test_that("produces correct results", {
  expect_equal(rscip:::scip_status_message(0), "SCIP_STATUS_UNKNOWN")
  expect_equal(rscip:::scip_status_message(1), "SCIP_STATUS_OPTIMAL")
  expect_equal(rscip:::scip_status_message(2), "SCIP_STATUS_INFEASIBLE")
  expect_equal(rscip:::scip_status_message(3), "SCIP_STATUS_UNBOUNDED")
  expect_equal(rscip:::scip_status_message(4), "SCIP_STATUS_INFORUNBD")
  expect_equal(rscip:::scip_status_message(10), "SCIP_STATUS_USERINTERRUPT")
  expect_equal(rscip:::scip_status_message(11), "SCIP_STATUS_TERMINATE")
  expect_equal(rscip:::scip_status_message(20), "SCIP_STATUS_NODELIMIT")
  expect_equal(rscip:::scip_status_message(21), "SCIP_STATUS_TOTALNODELIMIT")
  expect_equal(rscip:::scip_status_message(22), "SCIP_STATUS_STALLNODELIMIT")
  expect_equal(rscip:::scip_status_message(23), "SCIP_STATUS_TIMELIMIT")
  expect_equal(rscip:::scip_status_message(24), "SCIP_STATUS_MEMLIMIT")
  expect_equal(rscip:::scip_status_message(25), "SCIP_STATUS_GAPLIMIT")
  expect_equal(rscip:::scip_status_message(26), "SCIP_STATUS_PRIMALLIMIT")
  expect_equal(rscip:::scip_status_message(27), "SCIP_STATUS_DUALLIMIT")
  expect_equal(rscip:::scip_status_message(28), "SCIP_STATUS_SOLLIMIT")
  expect_equal(rscip:::scip_status_message(29), "SCIP_STATUS_BESTSOLLIMIT")
  expect_equal(rscip:::scip_status_message(30), "SCIP_STATUS_RESTARTLIMIT")
  expect_equal(rscip:::scip_status_message(999), "NOT RECOGNIZED")
})
