# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_scip_solve <- function(modelsense, obj, lb, ub, vtype, rhs, sense, A_i, A_j, A_x, gap = 0, time_limit = 1e+20, first_feasible = FALSE, presolve = TRUE, threads = 1L, verbose = TRUE, display_width = 143L) {
    .Call(`_rscip_rcpp_scip_solve`, modelsense, obj, lb, ub, vtype, rhs, sense, A_i, A_j, A_x, gap, time_limit, first_feasible, presolve, threads, verbose, display_width)
}

rcpp_scip_version <- function() {
    .Call(`_rscip_rcpp_scip_version`)
}

